Atualização de readme
fga-eps-mds/2022-2-CAPJu-Service pull request #32
Opened 2023-02-05 03:23 UTC by AntonioAldisio

2023-02-05 20:49 UTC, vitorAlves7 commented on README.md
>  O CAPJu é abreviação para _"Controle e Acompanhamento de Processos da Justiça"_, no qual trata-se de uma projeto de código aberto que tem como objetivo ajudar os usuários da 4ª vara cível da Justiça
aqui tem que trocar uma por um

2023-02-05 20:49 UTC, vitorAlves7 commented on README.md
> +- [Node.js](https://nodejs.org/en/) (Versão 14 ou superior) Como ambiente de execução de JavaScript.
Seria só versão 14 aqui

2023-02-05 20:49 UTC, vitorAlves7 commented on README.md
> +- [Sequelize](https://sequelize.org/) Como camada "ODM" / model
Aqui seria ORM, o modelo ODM é utilizado no mongoose

2023-02-05 20:49 UTC, vitorAlves7 commented on README.md
> +Para executar o projeto é recomendar executar os comandos na ordem de repositórios de back-end primeiro e front-end ao final. E cada um em um terminal diferente
Aqui seria "É recomendado?"

2023-02-05 20:49 UTC, vitorAlves7 commented on README.md
>  Pode ser utilizado o seguinte comando para inserir novas dependencias no sistema
Não precisa ter adição de dependência no readme

2023-02-06 05:11 UTC, DaviAntonio requested changes

2023-02-06 05:11 UTC, DaviAntonio commented on README.md
> +POSTGRES_HOST=
falta a env de CAPJU_EMAIL_PASSWORD

2023-02-06 05:11 UTC, DaviAntonio commented on README.md
> +Para executar o projeto é recomendar executar os comandos na ordem de repositórios de back-end primeiro e front-end ao final. E cada um em um terminal diferente
Ou então "é recomendável"

2023-02-06 05:20 UTC, DaviAntonio approved these changes

2023-02-06 05:21 UTC, merged